let input_modal_1 = $('#myModal .modal-body input');
let select_modal_1 = $('#myModal .modal-body select');
let username = $('#username');
let tel = $('#tel');
let email = $('#email');
let years = $('#year');
let day = $('#day');
let month = $('#month');
let pswd = $('#mdp');